/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class algorithm_jni_multi_JNIInheritVirtureForce */

#ifndef _Included_algorithm_jni_multi_JNIInheritVirtureForce
#define _Included_algorithm_jni_multi_JNIInheritVirtureForce
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     algorithm_jni_multi_JNIInheritVirtureForce
 * Method:    runNativeInherit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_algorithm_jni_multi_JNIInheritVirtureForce_runNativeInherit
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
