/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class algorithm_jni_multi_JNIAPSO */

#ifndef _Included_algorithm_jni_multi_JNIAPSO
#define _Included_algorithm_jni_multi_JNIAPSO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     algorithm_jni_multi_JNIAPSO
 * Method:    runNativePSO
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_algorithm_jni_multi_JNIAPSO_runNativePSO
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
