/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class algorithm_jni_multi_JNIInheritBase */

#ifndef _Included_algorithm_jni_multi_JNIInheritBase
#define _Included_algorithm_jni_multi_JNIInheritBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     algorithm_jni_multi_JNIInheritBase
 * Method:    runNativeInherit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_algorithm_jni_multi_JNIInheritBase_runNativeInherit
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
