/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class algorithm_jni_multi_JNIPSOBase */

#ifndef _Included_algorithm_jni_multi_JNIPSOBase
#define _Included_algorithm_jni_multi_JNIPSOBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     algorithm_jni_multi_JNIPSOBase
 * Method:    runNativePSO
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_algorithm_jni_multi_JNIPSOBase_runNativePSO
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
